#!/bin/bash
# ═══════════════════════════════════════════════════════════════════════════════
# Git Workflow for Team Collaboration
# ═══════════════════════════════════════════════════════════════════════════════
# Use this to push your changes step by step

echo "📋 Git Workflow Guide for Assignment 3"
echo ""
echo "============================================"
echo "MEMBER 1: Tasks 1, 2, 3"
echo "============================================"
echo ""
echo "Step 1: Create and push task1-vpc branch"
echo "git checkout -b task1-vpc"
echo "git add terraform/main.tf terraform/variables.tf terraform/outputs.tf"
echo "git commit -m 'Task 1: Custom VPC with subnets and NAT Gateway'"
echo "git push origin task1-vpc"
echo ""
echo "Step 2: Create PR on GitHub and merge when ready"
echo "git checkout main"
echo "git pull origin main"
echo ""
echo "Step 3: Create and push task2-ec2 branch"
echo "git checkout -b task2-ec2"
echo "git add terraform/"
echo "git commit -m 'Task 2: Security groups and EC2 instances'"
echo "git push origin task2-ec2"
echo ""
echo "Step 4: Create PR on GitHub and merge when ready"
echo "git checkout main"
echo "git pull origin main"
echo ""
echo "Step 5: Create and push task3-s3 branch"
echo "git checkout -b task3-s3"
echo "git add terraform/"
echo "git commit -m 'Task 3: S3 bucket, DynamoDB, and IAM roles'"
echo "git push origin task3-s3"
echo ""
echo "Step 6: Create PR on GitHub and merge when ready"
echo ""
echo ""
echo "============================================"
echo "MEMBER 2: Tasks 4, 5, 6"
echo "============================================"
echo ""
echo "Step 1: After Member 1 merges task1, start task4"
echo "git checkout main"
echo "git pull origin main"
echo "git checkout -b task4-asg"
echo "git add terraform/main.tf terraform/outputs.tf"
echo "git commit -m 'Task 4: ASG with CloudWatch alarms'"
echo "git push origin task4-asg"
echo ""
echo "Step 2: Create PR on GitHub and merge when ready"
echo "git checkout main"
echo "git pull origin main"
echo ""
echo "Step 3: Create and push task5-alb branch"
echo "git checkout -b task5-alb"
echo "git add terraform/"
echo "git commit -m 'Task 5: Application Load Balancer'"
echo "git push origin task5-alb"
echo ""
echo "Step 4: Create PR on GitHub and merge when ready"
echo "git checkout main"
echo "git pull origin main"
echo ""
echo "Step 5: Create and push task6-modules-packer branch"
echo "git checkout -b task6-modules-packer"
echo "git add terraform/modules/ terraform/packer/ terraform/module_usage.tf"
echo "git commit -m 'Task 6: Terraform modules and Packer AMI'"
echo "git push origin task6-modules-packer"
echo ""
echo "Step 6: Create PR on GitHub and merge when ready"
echo ""
echo ""
echo "============================================"
echo "BOTH MEMBERS: Final Steps"
echo "============================================"
echo ""
echo "After all tasks are merged to main:"
echo ""
echo "1. Pull latest main:"
echo "   git checkout main && git pull origin main"
echo ""
echo "2. Verify all files are present:"
echo "   ls -R terraform/"
echo ""
echo "3. Update terraform.tfvars with your IP:"
echo "   curl ifconfig.me  # Get your IP"
echo "   Edit: terraform/terraform.tfvars"
echo ""
echo "4. Initialize Terraform:"
echo "   cd terraform && terraform init"
echo ""
echo "5. Plan and review:"
echo "   terraform plan"
echo ""
echo "6. Apply all infrastructure:"
echo "   terraform apply -auto-approve"
echo ""
echo "7. After viva/grading, cleanup:"
echo "   terraform destroy -auto-approve"
echo ""
echo "✅ All done! Your infrastructure is ready for demo"
