#!/bin/bash
# ═══════════════════════════════════════════════════════════════════════════════
# Quick Reference: Terraform AWS Assignment 3
# ═══════════════════════════════════════════════════════════════════════════════

echo "🚀 DevOps Assignment 3 - Terraform AWS Infrastructure"
echo ""
echo "📋 SETUP STEPS:"
echo "1. Get your public IP: curl ifconfig.me"
echo "2. Update terraform.tfvars with your IP"
echo "3. cd terraform"
echo "4. terraform init"
echo "5. terraform plan"
echo "6. terraform apply -auto-approve"
echo ""
echo "🧪 VALIDATION COMMANDS:"
echo ""
echo "🔍 View all outputs:"
echo "   terraform output"
echo ""
echo "🌐 Get ALB DNS for testing:"
echo "   terraform output -raw alb_dns_name"
echo ""
echo "🖥️  SSH to web server:"
echo "   chmod 400 devops-key.pem"
echo "   ssh -i devops-key.pem ubuntu@\$(terraform output -raw web_server_public_ip)"
echo ""
echo "📊 View VPC, Subnets, and NAT:"
echo "   terraform output vpc_id"
echo "   terraform output public_subnet_ids"
echo "   terraform output private_subnet_ids"
echo "   terraform output nat_gateway_id"
echo ""
echo "📦 View S3 and DynamoDB (Task 3):"
echo "   terraform output s3_bucket_name"
echo "   terraform output dynamodb_table_name"
echo ""
echo "🔧 View ASG and Alarms (Task 4):"
echo "   terraform output asg_name"
echo "   terraform output cpu_high_alarm_name"
echo "   terraform output cpu_low_alarm_name"
echo ""
echo "⚖️  Scale ASG to 2 instances:"
echo "   terraform apply -var='desired_capacity=2' -auto-approve"
echo ""
echo "📊 Test load distribution:"
echo "   ALB=\$(terraform output -raw alb_dns_name)"
echo "   for i in {1..10}; do curl -s http://\$ALB | grep 'Instance ID'; done"
echo ""
echo "💪 Stress test (causes scale-out):"
echo "   ssh -i devops-key.pem ubuntu@<ASG_INSTANCE_IP>"
echo "   stress-ng --cpu 2 --timeout 300s &"
echo ""
echo "🏗️  Build Packer AMI (Task 6):"
echo "   cd packer"
echo "   packer init ."
echo "   packer build build.pkr.hcl"
echo ""
echo "🗑️  Cleanup:"
echo "   terraform destroy -auto-approve"
echo ""
echo "📝 For more details, see: terraform/README.md"
